### ISSUE TITLE
Please delete your solutions until the challenge concludes

### ISSUE THREAD

**Issue by veenaiyuri** [akshaaatt/IBM-Quantum-Challenge-Fall-2021#1]
Hi @akshaaatt ! I am the project owner of IBM Quantum Challenge Fall 2021. Can you please make your repo private or remove your solutions until the challenge concludes on Nov 5 12pm EDT? We do not want to spoil anything while the challenge is still on. Thank you for your understanding and quick action in advance.

**Comment by akshaaatt** [comment]
Thanks a lot for bringing this up! Removing the solutions ASAP.

**Comment by veenaiyuri** [comment]
Thank you! I appreciate your quick response!
